version: 2.1

workflows:
  test:
    jobs:
      - php-tests
#      - jest
#      - done:
#          requires: [php-tests, jest]

jobs:
  done:
    docker:
      - image: circleci/php:7.4-browsers
    steps:
      - checkout
      - run:
          name: Install composer dependencies
          command: composer install -o -n
      - run:
          name: upload to coveralls
          command: vendor/bin/php-coveralls -v  --exclude-no-stmt


  jest:
    machine:
      image: ubuntu-1604:202007-01
    environment:
      COVERALLS_PARALLEL: true
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: node_modules-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          name: Save dependancies cache
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run Jest tests
          command: |
            npm run test

  php-tests:
    docker:
      - image: circleci/php:7.4-browsers
    environment:
      COVERALLS_PARALLEL: true
    steps:
      - checkout
      - run:
          name: "Install Node.js"
          command: |
            curl -sSL "https://nodejs.org/dist/v10.15.0/node-v10.15.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v10.15.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo npm_install=8.1.1 sh

      - run:
          name: Setup environment variables
          command: |
            echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
      - restore_cache:
          name: Restore server dependencies cache
          key: deps-{{ .BuildNum }}
      - save_cache:
          name: Save server dependencies
          key: deps-{{ .BuildNum }}
          paths: |
            /usr/src/php/ext/intl/modules
            /usr/src/php/ext/mysqli/modules
            /usr/src/php/ext/zip/modules
      - run:
          name: Install composer dependencies
          command: composer install -o -n
      - save_cache:
          name: Save dependancies cache
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache
            - ~/.composer/cache
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Running PHP Unit
          command: |
           composer test:coverage
      - run:
          name: Run Jest tests
          command: |
            npm run test
      - store_test_results:
          path: /tmp/test-results/phpunit/
      - store_artifacts:
          path: /tmp/test-results/phpunit/coverage-report.xml
          destination: test-results
      - store_artifacts:
          path: coverage/phpunit
      - run:
          name: upload to coveralls
          command: vendor/bin/php-coveralls -v  --exclude-no-stmt
