version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

workflows:
  test:
    jobs:
      - unit-tests:
          filters:
            branches:
              ignore: /^.*-built$/
#      - upload-coveralls-report:
#          requires: [ unit-tests, jest ]

jobs:
  upload-coveralls-report:
    docker:
      - image: 'circleci/node:10.0.0'
    steps:
      - coveralls/upload:
          parallel_finished: true

  unit-tests:
    docker:
      - image: circleci/php:7.4-browsers
    steps:
      - checkout
      - run:
          name: "Install Node.js"
          command: |
            curl -sSL "https://nodejs.org/dist/latest/node-v17.0.1-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v17.0.1-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo npm_install=8.1.1 sh

      - run:
          name: Setup environment variables
          command: |
            echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
      - restore_cache:
          name: Restore server dependencies cache
          key: deps-{{ .BuildNum }}
      - save_cache:
          name: Save server dependencies
          key: deps-{{ .BuildNum }}
          paths: |
            /usr/src/php/ext/intl/modules
            /usr/src/php/ext/mysqli/modules
            /usr/src/php/ext/zip/modules
      - run:
          name: Install composer dependencies
          command: composer install -o -n
      - save_cache:
          name: Save dependancies cache
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache
            - ~/.composer/cache
      - run:
          name: Running PHP Unit
          command: composer test:coverage
      - store_test_results:
          path: /tmp/test-results/phpunit/
      - store_artifacts:
          path: /tmp/test-results/phpunit/coverage-report.xml
          destination: test-results
      - store_artifacts:
          path: coverage/phpunit
      - coveralls/upload:
          path_to_lcov: coverage/phpunit/clover.xml
  #          parallel_finished: true

